# Generated by Django 4.2.2 on 2023-06-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_firmware_updatecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='filename',
            field=models.FileField(upload_to='firmwares/'),
        ),
    ]
