# Generated by Django 4.2.2 on 2023-06-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_firmware_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmware',
            old_name='filename',
            new_name='firmware_file',
        ),
    ]
