# Generated by Django 4.2.2 on 2023-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_filename_firmware_firmware_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='filename',
            field=models.CharField(default='firmware_upload_file', max_length=255),
        ),
    ]
